version: '3.7'

services:
  back:
    build: ./backend/
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+psycopg2://${secrets.POSTGRES_USER}:${secrets.POSTGRES_PASSWORD}@db:5432/${secrets.POSTGRES_DB}"
      ALGORITHM: ${secrets.ALGORITHM}
      JWT_PASSPHRASE: ${secrets.SECRET_KEY}
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${secrets.POSTGRES_USER}
      POSTGRES_PASSWORD: ${secrets.POSTGRES_PASSWORD}
      POSTGRES_DB: ${secrets.POSTGRES_DB}
    ports:
      - "5432:5432"