version: '3.8'

services:
  db:
    container_name: db
    restart: always
    image: postgres:15
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"

  backend:
    restart: always
    build: ./backend
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      ALGORITHM: "${ALGORITHM}"
      SECRET_KEY: "${SECRET_KEY}"

  frontend:
      restart: always
      build:
        context: ./frontend
        dockerfile: Dockerfile
      depends_on:
        - backend
      ports:
        - "8080:8080"
      environment:
        API_URL: "ec2-13-37-212-138.eu-west-3.compute.amazonaws.com"