version: '3.8'

services:
  db:
    container_name: db
    networks:
      - fastapinetwork
    restart: always
    image: postgres:15
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"

  backend:
    restart: always
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - fastapinetwork
    environment:
      DATABASE_URL: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      ALGORITHM: "${ALGORITHM}"
      SECRET_KEY: "${SECRET_KEY}"

  networks:
    fastapinetwork:
      driver: bridge