name: main branch CI/CD

on:
  push:
    branches: [ "feat/api-cicd" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Build Docker Image
      uses: docker/compose-action@v1
      with:
        context: .
        push: true
        tags: ${{ github.repository }}:${{ env.GITHUB_SHA }}
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

    - name: Publish to GitHub Package Registry
      uses: docker/publish-action@v1
      with:
        tags: ${{ github.repository }}:${{ env.GITHUB_SHA }}
        registry: ghcr.io

#  deploy:
#    - name: Deploy to server
#      uses: appleboy/ssh-action@master
#      env:
#        GITHUB_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
#        GITHUB_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
#      with:
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.HOST_USER }}
#        password: ${{ secrets.HOST_PASSWORD }}
#        envs: GITHUB_USERNAME, GITHUB_TOKEN
#          script: |
#            docker login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_TOKEN
#            docker pull ghcr.io/my_github_username/my_repository_name/my_image_name:latest
#            docker stop containername
#            docker system prune -f
#            docker run --name containername -dit -p 3000:3000 ghcr.io/my_github_username/my_repository_name/my_image_name:latest