name: main branch CI/CD

on:
  push:
    branches: [ "feat/api-cicd" ]
  pull_request:
    branches: [ "main" ]

env:
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  ALGORITHM: ${{ secrets.ALGORITHM }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

#  deploy:
#    - name: Deploy to server
#      uses: appleboy/ssh-action@master
#      env:
#        GITHUB_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
#        GITHUB_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
#      with:
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.HOST_USER }}
#        password: ${{ secrets.HOST_PASSWORD }}
#        envs: GITHUB_USERNAME, GITHUB_TOKEN
#          script: |
#            docker login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_TOKEN
#            docker pull ghcr.io/my_github_username/my_repository_name/my_image_name:latest
#            docker stop containername
#            docker system prune -f
#            docker run --name containername -dit -p 3000:3000 ghcr.io/my_github_username/my_repository_name/my_image_name:latest